set(USER_EXECUTABLE_PROJECTS "tlocSimpleInput;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocInputCallbacks;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocObjLoader;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocSimplePhysics;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocSimpleQuad;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocSimpleSprite;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocMultipleSprites;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocTexturedFan")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocWindow;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocTexturedPhysics;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocRayPicking;")
list(APPEND USER_EXECUTABLE_PROJECTS "tlocRayPicking3d;")

set(USER_LIBRARY_PROJECTS "tlocSimpleLibrary")

set(USER_ASSETS_PATH "${CMAKE_SOURCE_DIR}/src/samplesAssetsPath.h")
