#------------------------------------------------------------------------------
# Over-ride the project name with the correct suffix (iff user hasn't modified
# it already)
if(${SOLUTION_NAME} STREQUAL "solution")
  set(SOLUTION_NAME "tlocSamples_${SOLUTION_BUILD_FOLDER_NAME}" CACHE STRING "You may change the name based on build configurations" FORCE)
  project(${SOLUTION_NAME})
endif()

#------------------------------------------------------------------------------
set(SOLUTION_EXECUTABLE_PROJECTS "tlocDynamicText;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocBloom;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocFontSprite;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocFontSpriteSheet;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocFPSCamera;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocInputCallbacks;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocJoysticks;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocKeyframeAnimation;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocMeshSorting;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocMultipleSprites;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocMultipleSystems;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocMultipleTextureCoords;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocNormalMapping;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocObjLoader;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocParallaxMapping;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocRayPicking;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocRayPicking3d;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocShadowMap;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimple3dTexture;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimplePhysics;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimpleQuad;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimpleRenderToTexture;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimpleSceneGraph;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimpleSprite;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimpleStereoscopic3d;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSkyBox;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocStaticText;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocSimpleInput;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocTexturedFan")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocTextureStream")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocTextureTypes")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocTexturedPhysics;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocVolumetric;")
list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocWindow;")

list(APPEND SOLUTION_EXECUTABLE_PROJECTS "tlocUtilsDFGenerator;")

set(SOLUTION_LIBRARY_PROJECTS "tlocSimpleLibrary")
